---
apiVersion: v1
offerings:
  - name: testing-deploy-arch-ibm-kms
    kind: solution
    catalog_id: f64499c8-eb50-4985-bf91-29f9e605a433
    offering_id: 85fdbd7a-8c77-4abd-b716-653a31f3aba9
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
